version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/payfood-app
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
